version: '3.8'

services:
  # PostgreSQL database for Synapse
  postgres:
    image: postgres:15
    container_name: matrix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: matrix_password
      POSTGRES_USER: matrix_user
      POSTGRES_DB: synapse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matrix_network

  # Synapse Matrix homeserver
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - synapse_data:/data
      - ./synapse/homeserver.yaml:/data/homeserver.yaml:ro
    environment:
      SYNAPSE_SERVER_NAME: localhost
      SYNAPSE_REPORT_STATS: "no"
    networks:
      - matrix_network
    ports:
      - "8008:8008"  # HTTP API
      - "8448:8448"  # HTTPS API

  # Sliding Sync Proxy
  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:latest
    container_name: matrix-sliding-sync
    restart: unless-stopped
    depends_on:
      - synapse
    environment:
      SYNCV3_SERVER: http://synapse:8008
      SYNCV3_DB: sqlite:///sliding-sync.db
      SYNCV3_SECRET: "secret"
      SYNCV3_BINDADDR: 0.0.0.0:8009
    volumes:
      - sliding_sync_data:/app
    networks:
      - matrix_network
    ports:
      - "8009:8009"  # Sliding Sync API

  # Element Web client (optional)
  element:
    image: vectorim/element-web:latest
    container_name: matrix-element
    restart: unless-stopped
    depends_on:
      - synapse
    environment:
      ELEMENT_CONFIG: |
        {
          "default_server_config": {
            "m.homeserver": {
              "base_url": "http://synapse:8008"
            },
            "m.identity_server": {
              "base_url": "https://vector.im"
            }
          },
          "disable_guests": true,
          "brand": "Local Matrix"
        }
    networks:
      - matrix_network
    ports:
      - "8080:80"  # Element Web UI

volumes:
  postgres_data:
  synapse_data:
  sliding_sync_data:

networks:
  matrix_network:
    driver: bridge 