// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/init.dart';
import 'api/logger.dart';
import 'api/platform.dart';
import 'api/tracing.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'matrix/authentication.dart';
import 'matrix/client.dart';
import 'matrix/rooms.dart';
import 'matrix/sync_service.dart';
import 'matrix/timelines.dart';
import 'matrix/user_serach.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/reqwest/tls.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CertificatePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FieldsFormatterForFilesPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Certificate
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  FieldsFormatterForFiles
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    dynamic raw,
  );

  @protected
  Certificate
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  FieldsFormatterForFiles
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  RustStreamSink<MessageUpdate> dco_decode_StreamSink_message_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RoomUpdate> dco_decode_StreamSink_room_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ClientConfig dco_decode_box_autoadd_client_config(dynamic raw);

  @protected
  Message dco_decode_box_autoadd_message(dynamic raw);

  @protected
  TracingConfiguration dco_decode_box_autoadd_tracing_configuration(
    dynamic raw,
  );

  @protected
  TracingFileConfiguration dco_decode_box_autoadd_tracing_file_configuration(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ClientConfig dco_decode_client_config(dynamic raw);

  @protected
  ClientError dco_decode_client_error(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Certificate>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Message> dco_decode_list_message(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RoomUpdate> dco_decode_list_room_update(dynamic raw);

  @protected
  List<TraceLogPacks> dco_decode_list_trace_log_packs(dynamic raw);

  @protected
  List<User> dco_decode_list_user(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  MessageType dco_decode_message_type(dynamic raw);

  @protected
  MessageUpdate dco_decode_message_update(dynamic raw);

  @protected
  MessageUpdateType dco_decode_message_update_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  Message? dco_decode_opt_box_autoadd_message(dynamic raw);

  @protected
  TracingFileConfiguration?
  dco_decode_opt_box_autoadd_tracing_file_configuration(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  List<Certificate>?
  dco_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  List<Message>? dco_decode_opt_list_message(dynamic raw);

  @protected
  RoomUpdate dco_decode_room_update(dynamic raw);

  @protected
  TraceLogPacks dco_decode_trace_log_packs(dynamic raw);

  @protected
  TracingConfiguration dco_decode_tracing_configuration(dynamic raw);

  @protected
  TracingFileConfiguration dco_decode_tracing_file_configuration(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateType dco_decode_update_type(dynamic raw);

  @protected
  User dco_decode_user(dynamic raw);

  @protected
  UserSearchResult dco_decode_user_search_result(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Certificate
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  FieldsFormatterForFiles
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    SseDeserializer deserializer,
  );

  @protected
  Certificate
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  FieldsFormatterForFiles
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MessageUpdate> sse_decode_StreamSink_message_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RoomUpdate> sse_decode_StreamSink_room_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_box_autoadd_client_config(
    SseDeserializer deserializer,
  );

  @protected
  Message sse_decode_box_autoadd_message(SseDeserializer deserializer);

  @protected
  TracingConfiguration sse_decode_box_autoadd_tracing_configuration(
    SseDeserializer deserializer,
  );

  @protected
  TracingFileConfiguration sse_decode_box_autoadd_tracing_file_configuration(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_client_config(SseDeserializer deserializer);

  @protected
  ClientError sse_decode_client_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Certificate>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RoomUpdate> sse_decode_list_room_update(SseDeserializer deserializer);

  @protected
  List<TraceLogPacks> sse_decode_list_trace_log_packs(
    SseDeserializer deserializer,
  );

  @protected
  List<User> sse_decode_list_user(SseDeserializer deserializer);

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  MessageType sse_decode_message_type(SseDeserializer deserializer);

  @protected
  MessageUpdate sse_decode_message_update(SseDeserializer deserializer);

  @protected
  MessageUpdateType sse_decode_message_update_type(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Message? sse_decode_opt_box_autoadd_message(SseDeserializer deserializer);

  @protected
  TracingFileConfiguration?
  sse_decode_opt_box_autoadd_tracing_file_configuration(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  List<Certificate>?
  sse_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  List<Message>? sse_decode_opt_list_message(SseDeserializer deserializer);

  @protected
  RoomUpdate sse_decode_room_update(SseDeserializer deserializer);

  @protected
  TraceLogPacks sse_decode_trace_log_packs(SseDeserializer deserializer);

  @protected
  TracingConfiguration sse_decode_tracing_configuration(
    SseDeserializer deserializer,
  );

  @protected
  TracingFileConfiguration sse_decode_tracing_file_configuration(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateType sse_decode_update_type(SseDeserializer deserializer);

  @protected
  User sse_decode_user(SseDeserializer deserializer);

  @protected
  UserSearchResult sse_decode_user_search_result(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    Certificate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    FieldsFormatterForFiles self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    Certificate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    FieldsFormatterForFiles self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_message_update_Sse(
    RustStreamSink<MessageUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_room_update_Sse(
    RustStreamSink<RoomUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_client_config(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tracing_configuration(
    TracingConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tracing_file_configuration(
    TracingFileConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_client_config(ClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_client_error(ClientError self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    List<Certificate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_update(
    List<RoomUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trace_log_packs(
    List<TraceLogPacks> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user(List<User> self, SseSerializer serializer);

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_message_type(MessageType self, SseSerializer serializer);

  @protected
  void sse_encode_message_update(MessageUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_message_update_type(
    MessageUpdateType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_message(
    Message? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_tracing_file_configuration(
    TracingFileConfiguration? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    List<Certificate>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_message(
    List<Message>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_update(RoomUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_trace_log_packs(TraceLogPacks self, SseSerializer serializer);

  @protected
  void sse_encode_tracing_configuration(
    TracingConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tracing_file_configuration(
    TracingFileConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_type(UpdateType self, SseSerializer serializer);

  @protected
  void sse_encode_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_user_search_result(
    UserSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  );
}
