// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/init.dart';
import 'api/logger.dart';
import 'api/matrix_client.dart';
import 'api/matrix_message.dart';
import 'api/matrix_room.dart';
import 'api/platform.dart';
import 'api/tracing.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'matrix/authentication.dart';
import 'matrix/client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/reqwest/tls.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CertificatePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FieldsFormatterForFilesPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Certificate
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  FieldsFormatterForFiles
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    dynamic raw,
  );

  @protected
  Certificate
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  FieldsFormatterForFiles
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogEntry> dco_decode_StreamSink_log_entry_Sse(dynamic raw);

  @protected
  RustStreamSink<MatrixRoomInfo> dco_decode_StreamSink_matrix_room_info_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RoomTimeline> dco_decode_StreamSink_room_timeline_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ClientConfig dco_decode_box_autoadd_client_config(dynamic raw);

  @protected
  MatrixClientConfig dco_decode_box_autoadd_matrix_client_config(dynamic raw);

  @protected
  MatrixMessage dco_decode_box_autoadd_matrix_message(dynamic raw);

  @protected
  RoomTimeline dco_decode_box_autoadd_room_timeline(dynamic raw);

  @protected
  TracingConfiguration dco_decode_box_autoadd_tracing_configuration(
    dynamic raw,
  );

  @protected
  TracingFileConfiguration dco_decode_box_autoadd_tracing_file_configuration(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ClientConfig dco_decode_client_config(dynamic raw);

  @protected
  ClientError dco_decode_client_error(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Certificate>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MatrixMessage> dco_decode_list_matrix_message(dynamic raw);

  @protected
  List<MatrixRoomInfo> dco_decode_list_matrix_room_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TraceLogPacks> dco_decode_list_trace_log_packs(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  MatrixClientConfig dco_decode_matrix_client_config(dynamic raw);

  @protected
  MatrixMessage dco_decode_matrix_message(dynamic raw);

  @protected
  MatrixRoomInfo dco_decode_matrix_room_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MatrixMessage? dco_decode_opt_box_autoadd_matrix_message(dynamic raw);

  @protected
  TracingFileConfiguration?
  dco_decode_opt_box_autoadd_tracing_file_configuration(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<Certificate>?
  dco_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    dynamic raw,
  );

  @protected
  RoomTimeline dco_decode_room_timeline(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw);

  @protected
  TraceLogPacks dco_decode_trace_log_packs(dynamic raw);

  @protected
  TracingConfiguration dco_decode_tracing_configuration(dynamic raw);

  @protected
  TracingFileConfiguration dco_decode_tracing_file_configuration(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Certificate
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  FieldsFormatterForFiles
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    SseDeserializer deserializer,
  );

  @protected
  Certificate
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  FieldsFormatterForFiles
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogEntry> sse_decode_StreamSink_log_entry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MatrixRoomInfo> sse_decode_StreamSink_matrix_room_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RoomTimeline> sse_decode_StreamSink_room_timeline_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_box_autoadd_client_config(
    SseDeserializer deserializer,
  );

  @protected
  MatrixClientConfig sse_decode_box_autoadd_matrix_client_config(
    SseDeserializer deserializer,
  );

  @protected
  MatrixMessage sse_decode_box_autoadd_matrix_message(
    SseDeserializer deserializer,
  );

  @protected
  RoomTimeline sse_decode_box_autoadd_room_timeline(
    SseDeserializer deserializer,
  );

  @protected
  TracingConfiguration sse_decode_box_autoadd_tracing_configuration(
    SseDeserializer deserializer,
  );

  @protected
  TracingFileConfiguration sse_decode_box_autoadd_tracing_file_configuration(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_client_config(SseDeserializer deserializer);

  @protected
  ClientError sse_decode_client_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Certificate>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MatrixMessage> sse_decode_list_matrix_message(
    SseDeserializer deserializer,
  );

  @protected
  List<MatrixRoomInfo> sse_decode_list_matrix_room_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TraceLogPacks> sse_decode_list_trace_log_packs(
    SseDeserializer deserializer,
  );

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  MatrixClientConfig sse_decode_matrix_client_config(
    SseDeserializer deserializer,
  );

  @protected
  MatrixMessage sse_decode_matrix_message(SseDeserializer deserializer);

  @protected
  MatrixRoomInfo sse_decode_matrix_room_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MatrixMessage? sse_decode_opt_box_autoadd_matrix_message(
    SseDeserializer deserializer,
  );

  @protected
  TracingFileConfiguration?
  sse_decode_opt_box_autoadd_tracing_file_configuration(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<Certificate>?
  sse_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    SseDeserializer deserializer,
  );

  @protected
  RoomTimeline sse_decode_room_timeline(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

  @protected
  TraceLogPacks sse_decode_trace_log_packs(SseDeserializer deserializer);

  @protected
  TracingConfiguration sse_decode_tracing_configuration(
    SseDeserializer deserializer,
  );

  @protected
  TracingFileConfiguration sse_decode_tracing_file_configuration(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    Certificate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    FieldsFormatterForFiles self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    Certificate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    FieldsFormatterForFiles self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_entry_Sse(
    RustStreamSink<LogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_matrix_room_info_Sse(
    RustStreamSink<MatrixRoomInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_room_timeline_Sse(
    RustStreamSink<RoomTimeline> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_client_config(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_matrix_client_config(
    MatrixClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_matrix_message(
    MatrixMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_room_timeline(
    RoomTimeline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tracing_configuration(
    TracingConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tracing_file_configuration(
    TracingFileConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_client_config(ClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_client_error(ClientError self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    List<Certificate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_matrix_message(
    List<MatrixMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_matrix_room_info(
    List<MatrixRoomInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trace_log_packs(
    List<TraceLogPacks> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_matrix_client_config(
    MatrixClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matrix_message(MatrixMessage self, SseSerializer serializer);

  @protected
  void sse_encode_matrix_room_info(
    MatrixRoomInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_matrix_message(
    MatrixMessage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_tracing_file_configuration(
    TracingFileConfiguration? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    List<Certificate>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_timeline(RoomTimeline self, SseSerializer serializer);

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_trace_log_packs(TraceLogPacks self, SseSerializer serializer);

  @protected
  void sse_encode_tracing_configuration(
    TracingConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tracing_file_configuration(
    TracingFileConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCertificate(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFieldsFormatterForFiles(
    int ptr,
  );
}
