// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../livekit_session.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attach_remote_track_if_new`, `attach_remote_tracks_from_participant`, `dispose_held`, `ensure_remote_publication_desired`, `ensure_webrtc_android_ready_for_connect`, `expected_i420_len`, `flush_audio`, `map_rotation`, `pack_i420_buffer_to_tight`, `push_i16_to_remote_ring`, `push_i420_tight`, `set_local_track_muted`, `spawn_remote_media_playout_task`, `spawn_remote_video_stream_consumer`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LiveKitHeld`

Future<void> livekitSessionConnect({
  required String url,
  required String token,
  required bool voiceOnly,
}) => RustLib.instance.api.crateApiLivekitSessionImpLivekitSessionConnect(
  url: url,
  token: token,
  voiceOnly: voiceOnly,
);

Future<void> livekitSessionClose() =>
    RustLib.instance.api.crateApiLivekitSessionImpLivekitSessionClose();

Future<String> livekitSessionConnectionState() => RustLib.instance.api
    .crateApiLivekitSessionImpLivekitSessionConnectionState();

Future<int> livekitSessionRemoteParticipantCount() => RustLib.instance.api
    .crateApiLivekitSessionImpLivekitSessionRemoteParticipantCount();

Future<void> livekitSessionSetMicrophoneMuted({required bool muted}) => RustLib
    .instance
    .api
    .crateApiLivekitSessionImpLivekitSessionSetMicrophoneMuted(muted: muted);

Future<void> livekitSessionSetCameraMuted({required bool muted}) => RustLib
    .instance
    .api
    .crateApiLivekitSessionImpLivekitSessionSetCameraMuted(muted: muted);

/// Publish a local camera track for sessions that connected with `voice_only: true`, so Flutter
/// can push I420 frames after the user turns the camera on.
Future<void> livekitSessionPublishLocalCameraTrack() => RustLib.instance.api
    .crateApiLivekitSessionImpLivekitSessionPublishLocalCameraTrack();

Future<void> livekitSessionPushAudioPcm16({
  required List<int> pcm,
  required int sampleRate,
  required int numChannels,
}) =>
    RustLib.instance.api.crateApiLivekitSessionImpLivekitSessionPushAudioPcm16(
      pcm: pcm,
      sampleRate: sampleRate,
      numChannels: numChannels,
    );

Future<void> livekitSessionPushVideoI420({
  required int width,
  required int height,
  required List<int> data,
  required PlatformInt64 timestampUs,
  required int rotationDegrees,
}) => RustLib.instance.api.crateApiLivekitSessionImpLivekitSessionPushVideoI420(
  width: width,
  height: height,
  data: data,
  timestampUs: timestampUs,
  rotationDegrees: rotationDegrees,
);

/// Pops up to [max_samples] mono PCM16 @ 48 kHz from the first remote microphone ring buffer.
Future<Int16List> livekitSessionPullRemoteAudioPcm16({
  required BigInt maxSamples,
}) => RustLib.instance.api
    .crateApiLivekitSessionImpLivekitSessionPullRemoteAudioPcm16(
      maxSamples: maxSamples,
    );

/// Pops the latest decoded remote camera frame (tight I420), if any, since the last pull.
Future<LivekitRemoteVideoI420> livekitSessionTryPullRemoteVideoI420() => RustLib
    .instance
    .api
    .crateApiLivekitSessionImpLivekitSessionTryPullRemoteVideoI420();
