// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tracing.dart';
part 'platform.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `build_tracing_filter`, `build`, `format_timestamp`, `get_global_init_state`, `make_broadcast_layer`, `make_file_layer`, `new`, `set_global_init_state`, `setup_lightweight_tokio_runtime`, `setup_multithreaded_tokio_runtime`, `targets`, `text_layers`, `write_filename`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BroadcastLogWriter`, `BroadcastMakeWriter`, `EventFormatter`, `LogTarget`, `LoggingCtx`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `eq`, `flush`, `format_event`, `format_fields`, `make_writer`, `partial_cmp`, `write`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_runtime_handle`

/// Sets up logs and the tokio runtime for the current application.
///
/// If `use_lightweight_tokio_runtime` is set to true, this will set up a
/// lightweight tokio runtime, for processes that have memory limitations (like
/// the NSE process on iOS). Otherwise, this can remain false, in which case a
/// multithreaded tokio runtime will be set up.
Future<void> initPlatform({
  required TracingConfiguration config,
  required bool useLightweightTokioRuntime,
}) => RustLib.instance.api.crateLoggerPlatformInitPlatform(
  config: config,
  useLightweightTokioRuntime: useLightweightTokioRuntime,
);

/// Updates the tracing subscriber with a new file writer based on the provided
/// configuration.
///
/// This method will throw if `init_platform` hasn't been called, or if it was
/// called with `write_to_files` set to `None`.
Future<void> reloadTracingFileWriter({
  required TracingFileConfiguration configuration,
}) => RustLib.instance.api.crateLoggerPlatformReloadTracingFileWriter(
  configuration: configuration,
);

/// Subscribe to tracing logs as a stream. Each error/info/debug/warn/trace line is sent to the
/// given sink. Intended for iOS simulator where logs do not appear in the Dart VM console;
/// the Flutter app can subscribe (only when running on iOS simulator) and print to console.
///
/// Must be called after `init_platform`. If called before init, the stream will receive no
/// events.
Stream<String> subscribeTracingLogs() =>
    RustLib.instance.api.crateLoggerPlatformSubscribeTracingLogs();

/// Subscribe to HTTP-only tracing logs (Matrix SDK HTTP client). Same as [subscribe_tracing_logs]
/// but only lines from `matrix_sdk::http_client` are sent. Use this to capture/intercept all HTTP
/// request/response logs for a "Network" tab or DevTools-style viewer (see e.g. [rhttp](https://codeberg.org/Tienisto/rhttp)).
///
/// For more detail (URI, method, status, duration), set [TraceLogPacks::matrix_sdk_http] when
/// initializing so `matrix_sdk::http_client` is at trace level.
///
/// Must be called after `init_platform`.
Stream<String> subscribeHttpTracingLogs() =>
    RustLib.instance.api.crateLoggerPlatformSubscribeHttpTracingLogs();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FieldsFormatterForFiles>>
abstract class FieldsFormatterForFiles implements RustOpaqueInterface {
  static Future<FieldsFormatterForFiles> default_() =>
      RustLib.instance.api.crateLoggerPlatformFieldsFormatterForFilesDefault();
}

@freezed
sealed class ClientError with _$ClientError implements FrbException {
  const ClientError._();

  const factory ClientError.generic({required String msg, String? details}) =
      ClientError_Generic;
}

enum FileRotation { minutely, hourly, daily, weekly, never }

/// A log pack can be used to set the trace log level for a group of multiple
/// log targets at once, for debugging purposes.
enum TraceLogPacks {
  /// Enables all the logs relevant to the event cache.
  eventCache,

  /// Enables all the logs relevant to the send queue.
  sendQueue,

  /// Enables all the logs relevant to the timeline.
  timeline,

  /// Enables all the logs relevant to the notification client.
  notificationClient,

  /// Enables trace-level logs for the Matrix SDK HTTP client (request/response, URI, method, status, duration).
  /// Use with [subscribe_http_tracing_logs] for a Network/DevTools-style HTTP log.
  matrixSdkHttp,
}

class TracingConfiguration {
  /// The desired log level.
  final LogLevel logLevel;

  /// All the log packs, that will be set to `TRACE` when they're enabled.
  final List<TraceLogPacks> traceLogPacks;

  /// Additional targets that the FFI client would like to use.
  ///
  /// This can include, for instance, the target names for created
  /// [`crate::tracing::Span`]. These targets will use the global log level by
  /// default.
  final List<String> extraTargets;

  /// Whether to log to stdout, or in the logcat on Android.
  final bool writeToStdoutOrSystem;

  /// If set, configures rotated log files where to write additional logs.
  final TracingFileConfiguration? writeToFiles;

  const TracingConfiguration({
    required this.logLevel,
    required this.traceLogPacks,
    required this.extraTargets,
    required this.writeToStdoutOrSystem,
    this.writeToFiles,
  });

  @override
  int get hashCode =>
      logLevel.hashCode ^
      traceLogPacks.hashCode ^
      extraTargets.hashCode ^
      writeToStdoutOrSystem.hashCode ^
      writeToFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TracingConfiguration &&
          runtimeType == other.runtimeType &&
          logLevel == other.logLevel &&
          traceLogPacks == other.traceLogPacks &&
          extraTargets == other.extraTargets &&
          writeToStdoutOrSystem == other.writeToStdoutOrSystem &&
          writeToFiles == other.writeToFiles;
}

/// Configuration to save logs to (rotated) log-files.
class TracingFileConfiguration {
  /// Base location for all the log files.
  final String path;

  /// Prefix for the log files' names.
  final String filePrefix;

  /// Optional suffix for the log file's names.
  final String? fileSuffix;

  /// Maximum number of rotated files.
  ///
  /// If not set, there's no max limit, i.e. the number of log files is
  /// unlimited.
  final BigInt? maxFiles;
  final FileRotation rotation;

  const TracingFileConfiguration({
    required this.path,
    required this.filePrefix,
    this.fileSuffix,
    this.maxFiles,
    required this.rotation,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      filePrefix.hashCode ^
      fileSuffix.hashCode ^
      maxFiles.hashCode ^
      rotation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TracingFileConfiguration &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          filePrefix == other.filePrefix &&
          fileSuffix == other.fileSuffix &&
          maxFiles == other.maxFiles &&
          rotation == other.rotation;
}
