// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> sendTextMessage({
  required String roomId,
  required String content,
}) => RustLib.instance.api.crateApiMatrixMessageSendTextMessage(
  roomId: roomId,
  content: content,
);

Future<String> sendFormattedMessage({
  required String roomId,
  required String content,
  required String formattedContent,
}) => RustLib.instance.api.crateApiMatrixMessageSendFormattedMessage(
  roomId: roomId,
  content: content,
  formattedContent: formattedContent,
);

Future<String> sendReaction({
  required String roomId,
  required String eventId,
  required String reaction,
}) => RustLib.instance.api.crateApiMatrixMessageSendReaction(
  roomId: roomId,
  eventId: eventId,
  reaction: reaction,
);

Future<bool> redactMessage({
  required String roomId,
  required String eventId,
  String? reason,
}) => RustLib.instance.api.crateApiMatrixMessageRedactMessage(
  roomId: roomId,
  eventId: eventId,
  reason: reason,
);
