// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<String>> getRoomMembers({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixRoomGetRoomMembers(roomId: roomId);

Future<bool> joinRoom({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixRoomJoinRoom(roomId: roomId);

Future<bool> leaveRoom({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixRoomLeaveRoom(roomId: roomId);

Future<bool> inviteUser({required String roomId, required String userId}) =>
    RustLib.instance.api.crateApiMatrixRoomInviteUser(
      roomId: roomId,
      userId: userId,
    );
