// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns JSON with ok/preview or ok/error keys (see matrix document_preview module).
Future<String> documentPreviewJson({
  required String extension_,
  required List<int> data,
}) => RustLib.instance.api.crateApiDocumentPreviewDocumentPreviewJson(
  extension_: extension_,
  data: data,
);
