// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Latest remote video frame as tightly packed I420 (full Y, then U, then V), matching the layout used for
/// [`imp::livekit_session_push_video_i420`].
class LivekitRemoteVideoI420 {
  final int width;
  final int height;
  final Uint8List data;

  const LivekitRemoteVideoI420({
    required this.width,
    required this.height,
    required this.data,
  });

  static Future<LivekitRemoteVideoI420> default_() => RustLib.instance.api
      .crateApiLivekitSessionLivekitRemoteVideoI420Default();

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivekitRemoteVideoI420 &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          data == other.data;
}
