// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../matrix/client.dart';
import '../matrix/rooms.dart';
import '../matrix/sync_service.dart';
import '../matrix/timelines.dart';
import '../matrix/user_serach.dart';
import '../rhttp/api/client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixClient>>
abstract class MatrixClient implements RustOpaqueInterface {
  /// Initialize the client with the given config. Returns a [MatrixClient] instance to use for
  /// all further operations (login, register, get_all_rooms, etc.).
  static Future<MatrixClient> configure({required ClientConfig config}) =>
      RustLib.instance.api.crateApiMatrixClientMatrixClientConfigure(
        config: config,
      );

  Future<String> createDirectRoom({required String userId});

  Future<String> createGroupRoom({
    required String name,
    required List<String> userIds,
  });

  /// Fetch all rooms the user is in. Uses the app stored in this client (from [MatrixClient::start_sync_service]).
  Future<List<RoomUpdate>> getAllRooms();

  Future<List<Message>> getOlderMessages({
    required String roomId,
    required int count,
  });

  Future<List<Message>> getTimelineItemsByRoomId({required String roomId});

  /// Whether the client has an active session.
  Future<bool> isClientAuthenticated();

  Future<String> joinRoom({required String roomId});

  Future<String> leaveRoom({required String roomId});

  /// Log in with username and password.
  Future<bool> login({required String username, required String password});

  /// Log out and clear the session.
  Future<bool> logout();

  /// Register a new account.
  Future<bool> register({required String username, required String password});

  Future<void> registerPusher({
    required String pushKey,
    required String appId,
    required String url,
    required String displayName,
    required String profileTag,
    required String lang,
    required String appDisplayName,
  });

  /// Restart the sync service after it has stopped (e.g. after long background). Safe to call repeatedly.
  Future<bool> restartSyncService();

  Future<UserSearchResult> searchUsers({required String query});

  /// Send a message. Returns the event_id. After success, call [MatrixClient::take_last_sent_room_update]
  /// to get the room update with the sent message as last (for updating the room list immediately).
  Future<String> sendMessage({required String roomId, required String content});

  /// Start the sync service (required for rooms and timeline to work).
  /// Stores the App in this client; rooms/timeline/sync state use it instead of global state.
  Future<bool> startSyncService();

  /// Subscribe to sync service state (Idle, Running, Terminated, Error, Offline).
  /// Call after [MatrixClient::start_sync_service]. When state changes, refresh rooms/timeline
  /// or show sync status; mirrors matrix-sdk-ffi SyncServiceStateObserver.
  Stream<SyncState> subscribeSyncState();

  /// Subscribe to room list updates (joined / invited / left). Uses the app stored in this client.
  Stream<RoomUpdate> subscribeToAllRoomUpdates();

  Stream<MessageUpdate> subscribeToTimelineUpdates({required String roomId});

  /// Takes the room update stored by the last successful [MatrixClient::send_message].
  /// Call this after send_message succeeds to update the room list with the correct last message.
  Future<RoomUpdate?> takeLastSentRoomUpdate();

  Future<void> unregisterPusher({
    required String pushKey,
    required String appId,
  });
}
