// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../matrix/client.dart';
import '../matrix/file_send_progress.dart';
import '../matrix/room_info.dart';
import '../matrix/rooms.dart';
import '../matrix/sync_service.dart';
import '../matrix/timelines.dart';
import '../matrix/user_serach.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixClient>>
abstract class MatrixClient implements RustOpaqueInterface {
  /// Cancels an in-progress [MatrixClient::send_timeline_file_with_progress] (upload / send).
  Future<void> cancelTimelineFileSend();

  /// Initialize the client with the given config. Returns a [MatrixClient] instance to use for
  /// all further operations (login, register, get_all_rooms, etc.).
  static Future<MatrixClient> configure({required ClientConfig config}) =>
      RustLib.instance.api.crateApiMatrixClientMatrixClientConfigure(
        config: config,
      );

  Future<String> createDirectRoom({required String userId});

  Future<String> createGroupRoom({
    required String name,
    required List<String> userIds,
  });

  /// Fetches decrypted media bytes for a timeline message (image/video/file/audio).
  /// `event_id` may be a server event id or a **local transaction id** for pending echoes.
  /// Set [thumbnail] to request a server-generated thumbnail when available (smaller for grid UI).
  Future<Uint8List> fetchRoomMessageMedia({
    required String roomId,
    required String eventId,
    required bool thumbnail,
  });

  /// Fetch all rooms the user is in. Uses the app stored in this client (from [MatrixClient::start_sync_service]).
  Future<List<RoomUpdate>> getAllRooms();

  /// Get the current user's display name (profile).
  Future<String?> getDisplayName();

  /// Returns the joined DM room id if a 1:1 direct room with this user already exists
  /// ([`matrix_sdk::Client::get_dm_room`]).
  Future<String?> getExistingDmRoomId({required String userId});

  /// Load older messages (paginate backwards). Updates the timeline list cache and pushes to
  /// subscribers so the UI receives the full list including newly loaded messages.
  Future<List<Message>> getOlderMessages({
    required String roomId,
    required int count,
  });

  /// Room summary, joined members (empty for DMs), and moderation flags for the current user.
  Future<RoomDetails> getRoomDetails({required String roomId});

  Future<List<Message>> getTimelineItemsByRoomId({required String roomId});

  /// Whether the client has an active session.
  Future<bool> isClientAuthenticated();

  Future<String> joinRoom({required String roomId});

  /// Remove a member from the room (kick). Requires sufficient power level.
  Future<void> kickRoomMember({required String roomId, required String userId});

  /// Leave the room and call `/forget` so it disappears from the client room list.
  Future<String> leaveAndForgetRoom({required String roomId});

  Future<String> leaveRoom({required String roomId});

  /// `m.room.message` events with `msgtype` **m.file** from the **event cache SQLite DB**
  /// (`get_room_events` / timeline persistence). Sent vs received uses sender vs logged-in user.
  Future<List<RoomFileItem>> listRoomFiles({
    required String roomId,
    required RoomFileFilter filter,
  });

  /// `m.text` / `m.notice` events whose body contains an HTTP(S) URL, with optional MSC4095 previews.
  Future<List<RoomLinkItem>> listRoomLinks({
    required String roomId,
    required RoomFileFilter filter,
  });

  /// MSC3381 unstable poll start events from the event cache (for room info index).
  Future<List<RoomPollItem>> listRoomPolls({
    required String roomId,
    required RoomFileFilter filter,
  });

  /// Log in with username and password.
  Future<bool> login({required String username, required String password});

  /// Log out and clear the session.
  Future<bool> logout();

  /// Redact a timeline message for **everyone** (`m.room.redaction`) or abort a matching local echo.
  ///
  /// Pass [event_id] for remote echoes, or [transaction_id] for a local row (matrix-sdk-ui picks redact vs abort).
  Future<void> redactTimelineEvent({
    required String roomId,
    required String eventId,
    required String transactionId,
    String? reason,
  });

  /// Register a new account.
  Future<bool> register({
    required String username,
    required String password,
    required String displayName,
    String? token,
  });

  Future<void> registerPusher({
    required String pushKey,
    required String appId,
    required String url,
    required String displayName,
    required String profileTag,
    required String lang,
    required String appDisplayName,
  });

  /// Restart the sync service after it has stopped (e.g. after long background). Safe to call repeatedly.
  Future<bool> restartSyncService();

  /// Retry sending after a recoverable failure ([Message::send_recoverable]).
  Future<void> retryFailedSend({
    required String roomId,
    required String transactionId,
  });

  /// Subscribe the sliding-sync room list to one room (latest events, required state).
  /// Call when the user opens a conversation (same as multiverse `subscribe_to_rooms` on focus).
  Future<void> roomListSubscribeToRooms({required String roomId});

  Future<UserSearchResult> searchUsers({required String query});

  /// Send a message through the UI timeline (local echo, offline errors, retry via [Self::retry_failed_send]).
  /// Returns the server event id once echoed; often empty immediately—UI should follow the timeline stream.
  Future<String> sendMessage({required String roomId, required String content});

  /// Send an MSC3381 unstable poll (`org.matrix.msc3381.poll.start`). Only allowed in non-DM rooms.
  Future<String> sendPoll({
    required String roomId,
    required String question,
    required List<String> answerTexts,
    required bool kindDisclosed,
    required BigInt maxSelections,
  });

  /// Submit votes for an unstable poll ([`UnstablePollResponseEventContent`]).
  Future<String> sendPollResponse({
    required String roomId,
    required String pollStartEventId,
    required List<String> answerIds,
  });

  /// Send a text reply to an existing timeline event (`m.in_reply_to`). Requires a server [event id](https://spec.matrix.org/latest/client-server-api/#event-structure), not a local transaction id.
  Future<String> sendReply({
    required String roomId,
    required String content,
    required String replyToEventId,
  });

  /// Send a file from a local path on the UI timeline.
  ///
  /// Sidecar DB: **`{session_path}/app/app_db.sqlite3`** (SQLCipher; same passphrase as Matrix stores).
  /// Table **`file_upload_cache`**: keyed by **SHA-256 of plaintext file bytes**. Plain rooms store
  /// reusable plain MXC URIs; encrypted rooms store a serialized `m.room.message` template after send
  /// so the same ciphertext/media can be resent with an updated caption without re-uploading.
  ///
  /// Plain reuse probes both MXCs on the server; E2EE reuse matches thumbnail JPEG bytes (when present)
  /// the same way. Timeline thumbnails for **images** and **videos** must come from the app: pass a JPEG
  /// path from the Dart `media` package as [`app_thumbnail_jpeg_path`]. PDF / office embedded thumbnails
  /// are still extracted in Rust when Pdfium / zip paths apply. Video compression is done in the app
  /// before send. **Encrypted** uploads use the SDK **send queue**; a fixed transaction id correlates
  /// queue updates, and the server `event_id` from `RoomSendQueueUpdate::SentEvent` loads the message
  /// into the cache when possible.
  Future<String> sendTimelineFile({
    required String roomId,
    required String filePath,
    String? caption,
    String? appThumbnailJpegPath,
  });

  /// Like [MatrixClient::send_timeline_file] but reports byte progress on `progress` and honours [MatrixClient::cancel_timeline_file_send].
  Stream<FileSendProgress> sendTimelineFileWithProgress({
    required String roomId,
    required String filePath,
    String? caption,
    String? appThumbnailJpegPath,
  });

  /// Set the current user's display name (profile).
  Future<void> setDisplayName({required String displayName});

  /// Change a member's power level (e.g. 50 = moderator, 100 = admin).
  Future<void> setRoomMemberPowerLevel({
    required String roomId,
    required String userId,
    required PlatformInt64 powerLevel,
  });

  /// Start the sync service (required for rooms and timeline to work).
  /// Stores the App in this client; rooms/timeline/sync state use it instead of global state.
  Future<bool> startSyncService();

  /// Subscribe to sync service state (Idle, Running, Terminated, Error, Offline).
  /// Call after [MatrixClient::start_sync_service]. When state changes, refresh rooms/timeline
  /// or show sync status; mirrors matrix-sdk-ffi SyncServiceStateObserver.
  /// No-ops if sync was not started (no panic).
  Stream<SyncState> subscribeSyncState();

  /// Subscribe to room list updates (joined / invited / left). Uses the app stored in this client.
  Stream<RoomUpdate> subscribeToAllRoomUpdates();

  /// Subscribe to the canonical room list. Emits the full list whenever it changes (sync or send_message).
  /// Call after [MatrixClient::start_sync_service]. Initial snapshot is sent immediately.
  Stream<List<RoomUpdate>> subscribeToRoomList();

  /// Subscribe to the canonical message list for a room. Emits the full list whenever it changes (timeline updates or send_message).
  /// Sends initial list immediately, then runs the timeline diff loop. Call after [MatrixClient::start_sync_service].
  Stream<List<Message>> subscribeToTimelineList({required String roomId});

  Stream<MessageUpdate> subscribeToTimelineUpdates({required String roomId});

  /// Takes the room update stored by the last successful [MatrixClient::send_message].
  /// Call this after send_message succeeds to update the room list with the correct last message.
  Future<RoomUpdate?> takeLastSentRoomUpdate();

  /// Toggle a reaction on a timeline message (`m.reaction`); returns `true` if added, `false` if removed.
  /// Pass [event_id] for remote echoes, or [transaction_id] for local echoes without an event id yet.
  Future<bool> toggleTimelineReaction({
    required String roomId,
    required String eventId,
    required String transactionId,
    required String reactionKey,
  });

  Future<void> unregisterPusher({
    required String pushKey,
    required String appId,
  });
}
