#!/usr/bin/env bash
# Install Pdfium (bblanchon/pdfium-binaries) and write env vars for Matrix Rust SDK.
# FFmpeg: install with Homebrew if missing (`brew install ffmpeg`).
#
# Usage:
#   ./sdk/tool/setup_native_media_env_macos.sh
#   source "$HOME/.matrix-sdk/native/env.sh"   # add this line to ~/.zshrc
#
set -euo pipefail

ROOT="${MATRIX_SDK_NATIVE_ROOT:-$HOME/.matrix-sdk/native}"
PDFIUM_INSTALL="$ROOT/pdfium"
ENV_FILE="$ROOT/env.sh"

mkdir -p "$ROOT"

ARCH="$(uname -m)"
case "$ARCH" in
  arm64) PDFIUM_ASSET="pdfium-mac-arm64.tgz" ;;
  x86_64) PDFIUM_ASSET="pdfium-mac-x64.tgz" ;;
  *)
    echo "Unsupported uname -m: $ARCH (use pdfium-mac-univ.tgz manually from releases)" >&2
    exit 1
    ;;
esac

if ! command -v curl >/dev/null; then
  echo "curl is required" >&2
  exit 1
fi

TAG="$(
  curl -fsSL https://api.github.com/repos/bblanchon/pdfium-binaries/releases/latest \
    | sed -n 's/.*"tag_name": "\([^"]*\)".*/\1/p' | head -1
)"
if [[ -z "${TAG}" ]]; then
  echo "Could not read latest pdfium-binaries release tag" >&2
  exit 1
fi

PDFIUM_LIB="$PDFIUM_INSTALL/lib/libpdfium.dylib"
if [[ ! -f "$PDFIUM_LIB" ]]; then
  echo "Downloading PDFium $TAG ($PDFIUM_ASSET)…"
  rm -rf "$PDFIUM_INSTALL"
  mkdir -p "$PDFIUM_INSTALL"
  TMP="$(mktemp -t pdfium.XXXXXX.tgz)"
  curl -fsSL -o "$TMP" \
    "https://github.com/bblanchon/pdfium-binaries/releases/download/${TAG}/${PDFIUM_ASSET}"
  tar -xzf "$TMP" -C "$PDFIUM_INSTALL"
  rm -f "$TMP"
fi

if [[ ! -f "$PDFIUM_LIB" ]]; then
  echo "Expected $PDFIUM_LIB after extract — check tarball layout" >&2
  exit 1
fi

# Directory that contains libpdfium.dylib (pdfium_render joins this dir + library name).
PDFIUM_DYLIB_DIR="$PDFIUM_INSTALL/lib"

FFMPEG_PATH=""
if command -v ffmpeg >/dev/null 2>&1; then
  FFMPEG_PATH="$(command -v ffmpeg)"
else
  echo "Warning: ffmpeg not on PATH. Install: brew install ffmpeg" >&2
fi

cat >"$ENV_FILE" <<EOF
# Generated by matrix-rust-dart-sdk/sdk/tool/setup_native_media_env_macos.sh
# Pdfium: $TAG
export PDFIUM_DYNAMIC_LIB_PATH="$PDFIUM_DYLIB_DIR"
export MATRIX_PDFIUM_DIR="$PDFIUM_DYLIB_DIR"
EOF
if [[ -n "$FFMPEG_PATH" ]]; then
  echo "export MATRIX_FFMPEG_PATH=\"$FFMPEG_PATH\"" >>"$ENV_FILE"
fi

echo "Wrote $ENV_FILE"
echo ""
echo "Add to ~/.zshrc:"
echo "  source \"$ENV_FILE\""
echo ""
echo "Then restart the terminal (or run: source \"$ENV_FILE\") before:"
echo "  - Running Flutter / Xcode (GUI apps do not load .zshrc; launch them from a shell or set vars in the scheme)"
echo "  - cargo test / CLI tools in this repo"
