// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ClientConfig {
  final String sessionPath;
  final String homeserverUrl;
  final List<Certificate>? rootCertificates;
  final String? proxy;
  final String? passphrase;

  /// When `false`, UI may show Matrix user ids without the `:server` suffix (e.g. `@user` only).
  final bool showHomeServerForUsername;

  /// Root directory for decrypted media cache (`thumbnails/`, `media/full/`, …). When `None` or
  /// empty, the SDK keeps the default in-memory media store (non-persistent, small LRU).
  final String? mediaCachePath;

  const ClientConfig({
    required this.sessionPath,
    required this.homeserverUrl,
    this.rootCertificates,
    this.proxy,
    this.passphrase,
    required this.showHomeServerForUsername,
    this.mediaCachePath,
  });

  @override
  int get hashCode =>
      sessionPath.hashCode ^
      homeserverUrl.hashCode ^
      rootCertificates.hashCode ^
      proxy.hashCode ^
      passphrase.hashCode ^
      showHomeServerForUsername.hashCode ^
      mediaCachePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientConfig &&
          runtimeType == other.runtimeType &&
          sessionPath == other.sessionPath &&
          homeserverUrl == other.homeserverUrl &&
          rootCertificates == other.rootCertificates &&
          proxy == other.proxy &&
          passphrase == other.passphrase &&
          showHomeServerForUsername == other.showHomeServerForUsername &&
          mediaCachePath == other.mediaCachePath;
}
