// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../rhttp/api/client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ClientConfig {
  final String sessionPath;
  final String homeserverUrl;
  final List<Certificate>? rootCertificates;
  final String? proxy;
  final String? passphrase;
  final RequestClient? rhttpClient;

  const ClientConfig({
    required this.sessionPath,
    required this.homeserverUrl,
    this.rootCertificates,
    this.proxy,
    this.passphrase,
    this.rhttpClient,
  });

  @override
  int get hashCode =>
      sessionPath.hashCode ^
      homeserverUrl.hashCode ^
      rootCertificates.hashCode ^
      proxy.hashCode ^
      passphrase.hashCode ^
      rhttpClient.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientConfig &&
          runtimeType == other.runtimeType &&
          sessionPath == other.sessionPath &&
          homeserverUrl == other.homeserverUrl &&
          rootCertificates == other.rootCertificates &&
          proxy == other.proxy &&
          passphrase == other.passphrase &&
          rhttpClient == other.rhttpClient;
}
