// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'timelines.dart';

/// A banned user row (for unban from room info).
class RoomBannedUserRow {
  final String userId;
  final String userIdDisplay;
  final String displayName;

  const RoomBannedUserRow({
    required this.userId,
    required this.userIdDisplay,
    required this.displayName,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ userIdDisplay.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomBannedUserRow &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userIdDisplay == other.userIdDisplay &&
          displayName == other.displayName;
}

/// Summary for the room info / settings UI.
class RoomDetails {
  final String roomId;
  final String displayName;
  final String topic;

  /// Room avatar MXC (`mxc://…`) from `m.room.avatar`; empty if unset.
  final String roomAvatarUrl;
  final bool isDirect;
  final bool isEncrypted;
  final int memberCount;
  final List<RoomMemberRow> members;
  final String currentUserId;
  final bool currentUserIsAdmin;
  final bool currentUserIsModerator;

  /// Whether the current user may send `m.room.avatar` per power levels + membership.
  final bool currentUserCanSetRoomAvatar;

  /// From the current user's membership + power levels (can call invite API).
  final bool currentUserCanInvite;

  /// From the current user's membership + power levels (can call ban / unban).
  final bool currentUserCanBan;

  /// Minimum power level required to invite (`m.room.power_levels`); defaults when unknown.
  final PlatformInt64 powerLevelInviteRequired;
  final PlatformInt64 powerLevelKickRequired;
  final PlatformInt64 powerLevelBanRequired;
  final List<RoomBannedUserRow> bannedUsers;

  /// Users with `invite` membership (not yet joined); from the local store after best-effort sync.
  final List<RoomInvitedMemberRow> invitedMembers;

  /// Distinct media attachment messages in the persisted event cache (all / sent+received).
  final int mediaIndexCount;

  /// Text messages in the cache whose body contains an HTTP(S) URL.
  final int linksIndexCount;

  /// MSC3381 poll start events in the cache.
  final int pollsIndexCount;

  const RoomDetails({
    required this.roomId,
    required this.displayName,
    required this.topic,
    required this.roomAvatarUrl,
    required this.isDirect,
    required this.isEncrypted,
    required this.memberCount,
    required this.members,
    required this.currentUserId,
    required this.currentUserIsAdmin,
    required this.currentUserIsModerator,
    required this.currentUserCanSetRoomAvatar,
    required this.currentUserCanInvite,
    required this.currentUserCanBan,
    required this.powerLevelInviteRequired,
    required this.powerLevelKickRequired,
    required this.powerLevelBanRequired,
    required this.bannedUsers,
    required this.invitedMembers,
    required this.mediaIndexCount,
    required this.linksIndexCount,
    required this.pollsIndexCount,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      displayName.hashCode ^
      topic.hashCode ^
      roomAvatarUrl.hashCode ^
      isDirect.hashCode ^
      isEncrypted.hashCode ^
      memberCount.hashCode ^
      members.hashCode ^
      currentUserId.hashCode ^
      currentUserIsAdmin.hashCode ^
      currentUserIsModerator.hashCode ^
      currentUserCanSetRoomAvatar.hashCode ^
      currentUserCanInvite.hashCode ^
      currentUserCanBan.hashCode ^
      powerLevelInviteRequired.hashCode ^
      powerLevelKickRequired.hashCode ^
      powerLevelBanRequired.hashCode ^
      bannedUsers.hashCode ^
      invitedMembers.hashCode ^
      mediaIndexCount.hashCode ^
      linksIndexCount.hashCode ^
      pollsIndexCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomDetails &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          displayName == other.displayName &&
          topic == other.topic &&
          roomAvatarUrl == other.roomAvatarUrl &&
          isDirect == other.isDirect &&
          isEncrypted == other.isEncrypted &&
          memberCount == other.memberCount &&
          members == other.members &&
          currentUserId == other.currentUserId &&
          currentUserIsAdmin == other.currentUserIsAdmin &&
          currentUserIsModerator == other.currentUserIsModerator &&
          currentUserCanSetRoomAvatar == other.currentUserCanSetRoomAvatar &&
          currentUserCanInvite == other.currentUserCanInvite &&
          currentUserCanBan == other.currentUserCanBan &&
          powerLevelInviteRequired == other.powerLevelInviteRequired &&
          powerLevelKickRequired == other.powerLevelKickRequired &&
          powerLevelBanRequired == other.powerLevelBanRequired &&
          bannedUsers == other.bannedUsers &&
          invitedMembers == other.invitedMembers &&
          mediaIndexCount == other.mediaIndexCount &&
          linksIndexCount == other.linksIndexCount &&
          pollsIndexCount == other.pollsIndexCount;
}

/// Filter for file rows from the cached timeline.
enum RoomFileFilter { all, received, sent }

/// One `m.room.message` attachment row from the event cache DB (file / image / video / audio).
class RoomFileItem {
  final String eventId;
  final String transactionId;
  final String sender;
  final String caption;
  final BigInt timestamp;
  final RoomMessageKind kind;

  /// True if [sender] is the logged-in user.
  final bool isOutgoing;

  /// File size in bytes from event `info.size`; `0` if unknown (e.g. missing or encrypted stub).
  final BigInt sizeBytes;

  const RoomFileItem({
    required this.eventId,
    required this.transactionId,
    required this.sender,
    required this.caption,
    required this.timestamp,
    required this.kind,
    required this.isOutgoing,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      transactionId.hashCode ^
      sender.hashCode ^
      caption.hashCode ^
      timestamp.hashCode ^
      kind.hashCode ^
      isOutgoing.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomFileItem &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          transactionId == other.transactionId &&
          sender == other.sender &&
          caption == other.caption &&
          timestamp == other.timestamp &&
          kind == other.kind &&
          isOutgoing == other.isOutgoing &&
          sizeBytes == other.sizeBytes;
}

/// Pending invite (`invite` membership) shown in room info.
class RoomInvitedMemberRow {
  final String userId;
  final String userIdDisplay;
  final String displayName;

  /// Member avatar MXC URI when known (`mxc://…`); empty if unset.
  final String avatarUrl;

  const RoomInvitedMemberRow({
    required this.userId,
    required this.userIdDisplay,
    required this.displayName,
    required this.avatarUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      userIdDisplay.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomInvitedMemberRow &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userIdDisplay == other.userIdDisplay &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl;
}

/// Text message row with at least one HTTP(S) URL; optional MSC4095 previews in [link_previews_json].
class RoomLinkItem {
  final String eventId;
  final String transactionId;
  final String sender;
  final String body;
  final BigInt timestamp;
  final bool isOutgoing;

  /// JSON array (`com.beeper.linkpreviews` / `m.url_previews` shape); `"[]"` when absent.
  final String linkPreviewsJson;

  /// `true` when the sender bundled link previews (MSC4095) on this event.
  final bool isLinkMessage;

  const RoomLinkItem({
    required this.eventId,
    required this.transactionId,
    required this.sender,
    required this.body,
    required this.timestamp,
    required this.isOutgoing,
    required this.linkPreviewsJson,
    required this.isLinkMessage,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      transactionId.hashCode ^
      sender.hashCode ^
      body.hashCode ^
      timestamp.hashCode ^
      isOutgoing.hashCode ^
      linkPreviewsJson.hashCode ^
      isLinkMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomLinkItem &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          transactionId == other.transactionId &&
          sender == other.sender &&
          body == other.body &&
          timestamp == other.timestamp &&
          isOutgoing == other.isOutgoing &&
          linkPreviewsJson == other.linkPreviewsJson &&
          isLinkMessage == other.isLinkMessage;
}

/// Role derived from power levels (creator / admin / moderator / user).
enum RoomMemberRoleDto { creator, administrator, moderator, user }

/// One joined member row for the room info screen.
class RoomMemberRow {
  final String userId;

  /// `user_id` formatted for labels; `user_id` stays canonical for kick / power APIs.
  final String userIdDisplay;
  final String displayName;

  /// Member avatar MXC URI when known (`mxc://…`); empty if unset.
  final String avatarUrl;

  /// Power level as integer (101 = creator / infinite).
  final PlatformInt64 powerLevel;
  final RoomMemberRoleDto role;
  final bool isSelf;

  /// Whether the **current** user may kick this member (server rules: own power ≥ kick, own > target).
  final bool currentUserCanKick;

  /// Whether the **current** user may ban this member (own power ≥ ban threshold, own > target).
  final bool currentUserCanBan;

  const RoomMemberRow({
    required this.userId,
    required this.userIdDisplay,
    required this.displayName,
    required this.avatarUrl,
    required this.powerLevel,
    required this.role,
    required this.isSelf,
    required this.currentUserCanKick,
    required this.currentUserCanBan,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      userIdDisplay.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      powerLevel.hashCode ^
      role.hashCode ^
      isSelf.hashCode ^
      currentUserCanKick.hashCode ^
      currentUserCanBan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomMemberRow &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userIdDisplay == other.userIdDisplay &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          powerLevel == other.powerLevel &&
          role == other.role &&
          isSelf == other.isSelf &&
          currentUserCanKick == other.currentUserCanKick &&
          currentUserCanBan == other.currentUserCanBan;
}

/// One `org.matrix.msc3381.poll.start` row from the event cache (group room index).
class RoomPollItem {
  final String eventId;
  final String transactionId;
  final String sender;
  final String question;
  final BigInt timestamp;
  final bool isOutgoing;

  const RoomPollItem({
    required this.eventId,
    required this.transactionId,
    required this.sender,
    required this.question,
    required this.timestamp,
    required this.isOutgoing,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      transactionId.hashCode ^
      sender.hashCode ^
      question.hashCode ^
      timestamp.hashCode ^
      isOutgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomPollItem &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          transactionId == other.transactionId &&
          sender == other.sender &&
          question == other.question &&
          timestamp == other.timestamp &&
          isOutgoing == other.isOutgoing;
}

/// Partial update for [`m.room.power_levels`](https://spec.matrix.org/latest/client-server-api/#mroompower_levels).
/// Only set fields you want to change; others stay unchanged on the server.
class RoomPowerLevelSettingsPatch {
  final PlatformInt64? ban;
  final PlatformInt64? invite;
  final PlatformInt64? kick;
  final PlatformInt64? redact;
  final PlatformInt64? eventsDefault;
  final PlatformInt64? stateDefault;
  final PlatformInt64? usersDefault;

  const RoomPowerLevelSettingsPatch({
    this.ban,
    this.invite,
    this.kick,
    this.redact,
    this.eventsDefault,
    this.stateDefault,
    this.usersDefault,
  });

  @override
  int get hashCode =>
      ban.hashCode ^
      invite.hashCode ^
      kick.hashCode ^
      redact.hashCode ^
      eventsDefault.hashCode ^
      stateDefault.hashCode ^
      usersDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomPowerLevelSettingsPatch &&
          runtimeType == other.runtimeType &&
          ban == other.ban &&
          invite == other.invite &&
          kick == other.kick &&
          redact == other.redact &&
          eventsDefault == other.eventsDefault &&
          stateDefault == other.stateDefault &&
          usersDefault == other.usersDefault;
}
