// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'timelines.dart';

class RoomUpdate {
  final String roomId;
  final String? rawName;
  final String? displayName;

  /// Room avatar MXC from `m.room.avatar` when known.
  final String? avatarUrl;
  final bool? isDm;
  final UpdateType updateType;
  final BigInt? unreadNotifications;
  final BigInt? unreadHighlight;
  final BigInt? unreadMentions;
  final BigInt? unreadMessages;
  final Message? message;

  const RoomUpdate({
    required this.roomId,
    this.rawName,
    this.displayName,
    this.avatarUrl,
    this.isDm,
    required this.updateType,
    this.unreadNotifications,
    this.unreadHighlight,
    this.unreadMentions,
    this.unreadMessages,
    this.message,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      rawName.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode ^
      isDm.hashCode ^
      updateType.hashCode ^
      unreadNotifications.hashCode ^
      unreadHighlight.hashCode ^
      unreadMentions.hashCode ^
      unreadMessages.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomUpdate &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          rawName == other.rawName &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl &&
          isDm == other.isDm &&
          updateType == other.updateType &&
          unreadNotifications == other.unreadNotifications &&
          unreadHighlight == other.unreadHighlight &&
          unreadMentions == other.unreadMentions &&
          unreadMessages == other.unreadMessages &&
          message == other.message;
}

enum UpdateType { joined, left, invited, knocked, banned }
