// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'timelines.dart';

/// Summary for the room info / settings UI.
class RoomDetails {
  final String roomId;
  final String displayName;
  final String topic;
  final bool isDirect;
  final bool isEncrypted;
  final int memberCount;
  final List<RoomMemberRow> members;
  final String currentUserId;
  final bool currentUserIsAdmin;
  final bool currentUserIsModerator;

  const RoomDetails({
    required this.roomId,
    required this.displayName,
    required this.topic,
    required this.isDirect,
    required this.isEncrypted,
    required this.memberCount,
    required this.members,
    required this.currentUserId,
    required this.currentUserIsAdmin,
    required this.currentUserIsModerator,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      displayName.hashCode ^
      topic.hashCode ^
      isDirect.hashCode ^
      isEncrypted.hashCode ^
      memberCount.hashCode ^
      members.hashCode ^
      currentUserId.hashCode ^
      currentUserIsAdmin.hashCode ^
      currentUserIsModerator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomDetails &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          displayName == other.displayName &&
          topic == other.topic &&
          isDirect == other.isDirect &&
          isEncrypted == other.isEncrypted &&
          memberCount == other.memberCount &&
          members == other.members &&
          currentUserId == other.currentUserId &&
          currentUserIsAdmin == other.currentUserIsAdmin &&
          currentUserIsModerator == other.currentUserIsModerator;
}

/// Filter for file rows from the cached timeline.
enum RoomFileFilter { all, received, sent }

/// One `m.room.message` attachment row from the event cache DB (file / image / video / audio).
class RoomFileItem {
  final String eventId;
  final String transactionId;
  final String sender;
  final String caption;
  final BigInt timestamp;
  final RoomMessageKind kind;

  /// True if [sender] is the logged-in user.
  final bool isOutgoing;

  /// File size in bytes from event `info.size`; `0` if unknown (e.g. missing or encrypted stub).
  final BigInt sizeBytes;

  const RoomFileItem({
    required this.eventId,
    required this.transactionId,
    required this.sender,
    required this.caption,
    required this.timestamp,
    required this.kind,
    required this.isOutgoing,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      transactionId.hashCode ^
      sender.hashCode ^
      caption.hashCode ^
      timestamp.hashCode ^
      kind.hashCode ^
      isOutgoing.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomFileItem &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          transactionId == other.transactionId &&
          sender == other.sender &&
          caption == other.caption &&
          timestamp == other.timestamp &&
          kind == other.kind &&
          isOutgoing == other.isOutgoing &&
          sizeBytes == other.sizeBytes;
}

/// Role derived from power levels (creator / admin / moderator / user).
enum RoomMemberRoleDto { creator, administrator, moderator, user }

/// One joined member row for the room info screen.
class RoomMemberRow {
  final String userId;
  final String displayName;

  /// Power level as integer (101 = creator / infinite).
  final PlatformInt64 powerLevel;
  final RoomMemberRoleDto role;
  final bool isSelf;

  /// Whether the **current** user may kick this member (server rules: own power ≥ kick, own > target).
  final bool currentUserCanKick;

  const RoomMemberRow({
    required this.userId,
    required this.displayName,
    required this.powerLevel,
    required this.role,
    required this.isSelf,
    required this.currentUserCanKick,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      powerLevel.hashCode ^
      role.hashCode ^
      isSelf.hashCode ^
      currentUserCanKick.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomMemberRow &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          powerLevel == other.powerLevel &&
          role == other.role &&
          isSelf == other.isSelf &&
          currentUserCanKick == other.currentUserCanKick;
}
