// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sync service state, mirroring the matrix-sdk-ffi SyncServiceState.
/// Notify the client when this changes so it can refresh rooms/timeline or show sync status.
enum SyncState { idle, running, terminated, error, offline }
