// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Kind of Matrix event that produced the notification.
enum SyncNotificationKind {
  message,
  invite,

  /// MatrixRTC / Element Call `m.rtc.notification` (incoming call UI).
  incomingCall,
  other,
}

/// Summary of a sync notification for local/system UI (titles, dedupe).
class SyncNotificationSummary {
  final String roomId;
  final String? roomDisplayName;
  final SyncNotificationKind kind;
  final String senderId;
  final String? senderDisplayName;
  final String bodyPreview;
  final bool isHighlight;
  final bool isNoisy;
  final String eventId;

  /// `true` when the RTC notification requests ringing (vs silent banner).
  final bool incomingCallRing;

  const SyncNotificationSummary({
    required this.roomId,
    this.roomDisplayName,
    required this.kind,
    required this.senderId,
    this.senderDisplayName,
    required this.bodyPreview,
    required this.isHighlight,
    required this.isNoisy,
    required this.eventId,
    required this.incomingCallRing,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      roomDisplayName.hashCode ^
      kind.hashCode ^
      senderId.hashCode ^
      senderDisplayName.hashCode ^
      bodyPreview.hashCode ^
      isHighlight.hashCode ^
      isNoisy.hashCode ^
      eventId.hashCode ^
      incomingCallRing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncNotificationSummary &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          roomDisplayName == other.roomDisplayName &&
          kind == other.kind &&
          senderId == other.senderId &&
          senderDisplayName == other.senderDisplayName &&
          bodyPreview == other.bodyPreview &&
          isHighlight == other.isHighlight &&
          isNoisy == other.isNoisy &&
          eventId == other.eventId &&
          incomingCallRing == other.incomingCallRing;
}
