// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class User {
  final String userId;

  /// `user_id` formatted for UI (homeserver suffix may be hidden).
  final String userIdDisplay;
  final String? displayName;
  final String? avatarUrl;

  const User({
    required this.userId,
    required this.userIdDisplay,
    this.displayName,
    this.avatarUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      userIdDisplay.hashCode ^
      displayName.hashCode ^
      avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userIdDisplay == other.userIdDisplay &&
          displayName == other.displayName &&
          avatarUrl == other.avatarUrl;
}

class UserSearchResult {
  final List<User> users;
  final bool limited;

  const UserSearchResult({required this.users, required this.limited});

  @override
  int get hashCode => users.hashCode ^ limited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserSearchResult &&
          runtimeType == other.runtimeType &&
          users == other.users &&
          limited == other.limited;
}
